### ISSUE TITLE
Use library on Seeeduino Xiao ble sense

### ISSUE THREAD

**Issue by ScrapTech** [cujomalainey/antplus-arduino#33]
Hi

I am trying to make an antplus sensor to send data to my garmin edge.
For this I was going to use the Seeed Xiao BLE sense board (nRF52840) together with the antplus-arduino library.

I installed the Seeed Xiao, the antplus library and ant library on the arduino IDE as described in following link: [Getting Started with XIAO BLE (Sense) - Seeed Wiki 1](https://wiki.seeedstudio.com/XIAO_BLE/)
Now I can upload example projects from seeeduino to the board and I can compile examples from the antplus library on other boards.

Whenever I try to compile an example from the antplus library on the seeeduino board, I get following errors:

![image](https://user-images.githubusercontent.com/70166175/181843202-9d4266bd-15d0-47c4-89d6-5ea981d1399f.png)

When I look in the header files of the seeeduino board, I noticed indeed that the Serial was defined as UART1:
![image](https://user-images.githubusercontent.com/70166175/181843281-eb9a35e3-ed7b-47f4-a657-0cef7e4a2dbb.png)
It seems that the antplus library can not handle this, and does not recognize UART1 as a type?

Thanks in advance for any help!

**Comment by cujomalainey** [comment]
Hi, I'll take a look into this, looks like a minor config issue. Are you using Arduino or mbed as your primary OS?

**Comment by ScrapTech** [comment]
Thank you! I am using Arduino as my primary OS

**Comment by cujomalainey** [comment]
Figured out the issue, its because the board is using mbed under the arduino HAL, so the system is having type collisions. I'll push a fix later tonight.

Also are you planning to use ANT on the Seeed chip or an external D52 chip?

**Comment by ScrapTech** [comment]
I'm planning to use the seeed chip itself, not an external one.

**Comment by cujomalainey** [comment]
Got it, best of luck with flashing the softdevice, i have seen mixed results. I should have a test fix for you in a few hours.

**Comment by cujomalainey** [comment]
I pushed a fix to ant-arduino, can you test it out?

https://github.com/cujomalainey/ant-arduino/commit/afcbca69050a3019ded8e7b121e1b55b35006a80

**Comment by ScrapTech** [comment]
It compiles now indeed and I'm able to upload it! Thanks!
I'm not able to pair it with my garmin edge just yet, so I don't know it it actually sending anything (I'm trying the bicyclepower sensor example to start with).
I'll keep you touch.
Thanks again!

**Comment by cujomalainey** [comment]
Sounds good, I'll cut a micro release once I fix the gcc complaints about how I defined the macro, in the meantime I'll close this. Let me know if you have anymore problems, best of luck.
